version: "3.3"
services:
  wiremock:
    build:
      context: .
    ports:
      - "8088:8080"
      - "8443:8443"
    volumes:
      - ./__files:/home/wiremock/__files
      - ./mappings:/home/wiremock/mappings
